### ISSUE TITLE
Getting prompted for github credentials when installing from requirements.yml or playbook

### ISSUE THREAD

**Issue by DMcP89** [gantsign/ansible_role_helm#105]
When I install this role directly it installs with no issues:
```
ansible-galaxy install gantsign.helm
Starting galaxy role install process
- downloading role 'helm', owned by gantsign
- downloading role from https://github.com/gantsign/ansible_role_helm/archive/2.12.0.tar.gz
- extracting gantsign.helm to /home/dave/.ansible/roles/gantsign.helm
- gantsign.helm (2.12.0) was installed successfully
```

However when I try to install it from a [requirements.yml](https://github.com/DMcP89/dotfiles/blob/dev/requirements.yml) file I am prompted for my github credentials:
```
ansible-galaxy install -r requirements.yml
Starting galaxy role install process
Username for 'https://github.com':
```
I see the same when allowing ansible to attempt to install the role automatically from a [playbook](https://github.com/DMcP89/dotfiles/blob/dev/ansible-playbooks/apt-packages.yml) as well:
```
Run cd $GITHUB_WORKSPACE
Installing dotfiles from Tag: 16[5](https://github.com/DMcP89/dotfiles/actions/runs/5180627912/jobs/9335045335#step:3:6)5c81
-----------------------
Installing ansible
-----------------------
Installing ansible dependencies
Warning: : - gantsign.helm was NOT installed successfully: - command
/usr/bin/git clone https://github.com/gantsign/ansible-role-helm.git
gantsign.helm failed in directory /home/runner/.ansible/tmp/ansible-
local-1[6](https://github.com/DMcP89/dotfiles/actions/runs/5180627912/jobs/9335045335#step:3:7)6[8](https://github.com/DMcP89/dotfiles/actions/runs/5180627912/jobs/9335045335#step:3:9)tozu0i6o/tmpdx8oliyt (rc=[12](https://github.com/DMcP89/dotfiles/actions/runs/5180627912/jobs/9335045335#step:3:13)8) - Cloning into 'gantsign.helm'...
fatal: could not read Username for 'https://github.com/': No such device or
address
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Starting galaxy role install process
make: *** [Makefile:21: install] Error 1
Error: Process completed with exit code 2.
```
Not sure if this is due to something with ansible or with the role. Any idea what might cause this?

**Comment by freemanjp** [comment]
Looks like you've configured your requirements file to clone the Git repository, whereas when you installed it directly via the CLI it downloads the `tar.gz` instead.

Either change your requirements file to:
```yaml
---
roles:
  - name: gantsign.helm
  - name: gantsign.golang
  - name: githubixx.kubectl
```
So it downloads the `tar.gz` instead of cloning the repo.

Or set up https://github.com/git-ecosystem/git-credential-manager and configure credentials for GitHub so it can clone the repo. Alternatively, you could change the `requirements.yml` to use SSH Git URLs (e.g. `git@github.com:gantsign/ansible_role_helm.git`) and configure an SSH key for GitHub access.

Note: your requirements file also has the repo name wrong it should be https://github.com/gantsign/ansible_role_helm.git (underscores)
 not https://github.com/gantsign/ansible-role-helm.git.

**Comment by DMcP89** [comment]
That did the trick. Thanks for the help!
